### PR TITLE
Entire repo awaiting reveiw

### PR DESCRIPTION
**Pull request by IsaacLeeWebDev**
First PR! See Database/ and test/ directories for real changes

### CODE REVIEW

**Comment by IsaacLeeWebDev** [comment]
@ac251

**Comment by ac251** [comment]
Database code looks good. A couple things to consider:

-- you want to have a script you can run, like, say, 'npm run seedDb' or something like that. It could totally make use of the given methods, but you'll want to be able to let anyone who clones the repo to seed db easily.

--There are other faker random things interpolated in the restaurant code, with the result that your random restaurant names after the first are not the same as the group's. I can see three potential solutions:

  1. refactor to do all restaurant naming before you do anything else random
  2. start with the restaurant names json data
  3. import faker twice and refactor to use the other instance of faker for all but the restaurant names

**Comment by ac251** [comment]
lines 43 - 44, you're trying to repeatedly do an async operation inside a for loop. Not sure how that will work out. COnsider refactoring to turn your fake data into csv and load it that way

**Comment by IsaacLeeWebDev** [comment]
> Database code looks good. A couple things to consider:
> 
> -- you want to have a script you can run, like, say, 'npm run seedDb' or something like that. It could totally make use of the given methods, but you'll want to be able to let anyone who clones the repo to seed db easily.
> 
> --There are other faker random things interpolated in the restaurant code, with the result that your random restaurant names after the first are not the same as the group's. I can see three potential solutions:
> 
> 1. refactor to do all restaurant naming before you do anything else random
> 2. start with the restaurant names json data
> 3. import faker twice and refactor to use the other instance of faker for all but the restaurant names

Took option 2. We may want to run that by Shi Hao. Let me know what you think of that.

**Comment by ac251** [comment]
That sounds good to me but if Shi Hao has anything to say def let me know!

**Pull request merged**
